#!/bin/sh
#

killproc() {
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
}

read CMDLINE < /proc/cmdline
for x in $CMDLINE; do
        case $x in
        qwindow=false)
		echo "qwindow disabled"
		exit 0;
                ;;
        esac
done

case "$1" in
  start)
	export QT_QPA_EGLFS_INTEGRATION=eglfs_kms
        /usr/share/qt5/examples/wayland/qwindow-compositor/qwindow-compositor -platform eglfs &
  ;;

  stop)
        echo "Stopping qwindow"
	export QT_QPA_EGLFS_INTEGRATION=none
        killproc qwindow-compositor
  ;;

  *)
        echo "usage: $0 { start | stop }"
  ;;
esac

exit 0
