#*******************************************************************************
#* FILE PURPOSE: Top level makefile for Creating Component Libraries and example 
#*               binaries
#*******************************************************************************
#* FILE NAME: makefile
#*
#* DESCRIPTION: Defines Compiler tools paths, libraries , Build Options 
#*
#*
#*******************************************************************************
#*
# (Mandatory) Specify where various tools are installed.

ifndef MAKE
export MAKE = make
endif

ifndef ECHO
export ECHO = echo
endif

all: __PDK_ALL_TARGETS__
clean: __PDK_CLEAN_TARGETS__
