-include ../../Rules.make

ENV_SETUP ?= ../../linux-devkit/environment-setup
DESTDIR ?=

all: release

lenet_mnist:
	${SDK_PATH_NATIVE}/usr/share/glow/bin/image-classifier ${SDK_PATH_NATIVE}/usr/share/glow/tests/images/mnist/1_1008.png -m=mnist.onnx -image-mode=0to1 -model-input-name=data_0 -emit-bundle ./ -cpu -target armv7l-unknown-linux-gnueabihf   -network-name="lenet_mnist"

release: lenet_mnist
	@. ${ENV_SETUP}; \
	make

clean:
	@. ${ENV_SETUP}; \
        make clean
	rm lenet_mnist.*
