#!/bin/sh
DAEMON=/usr/sbin/udhcpd
NAME=udhcpd
DESC="Busybox UDHCP Server"
DHCPD_OPTS="-S"
DHCPD_CONF="/etc/udhcpd.conf"

test -f $DAEMON || exit 1

# Include defaults if available
if [ -f /etc/default/udhcpd ] ; then
        . /etc/default/udhcpd
fi

if [ "$DHCPD_ENABLED" = "no" ]; then
    echo $NAME: Disabled. Edit /etc/default/udhcpd to enable it.
    exit 0;
fi

set -e

case "$1" in
    start)
        echo -n "starting $DESC: $NAME... "
	if [ ! -z $DHCPD_CONF ] && [ ! -f $DHCPD_CONF ]; then
		echo "error: $DHCPD_CONF is missing."
		exit 1
	fi
	/sbin/start-stop-daemon -S -b -n $NAME -a $DAEMON -- $DHCPD_OPTS $DHCPD_CONF
	echo "done."
	;;
    stop)
        echo -n "stopping $DESC: $NAME... "
	/sbin/start-stop-daemon -K -n $NAME
	echo "done."
	;;
    restart)
        echo "restarting $DESC: $NAME... "
 	$0 stop
	$0 start
	echo "done."
	;;
    reload)
    	echo -n "reloading $DESC: $NAME... "
    	killall -HUP $(basename ${DAEMON})
	echo "done."
	;;
    *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
	;;
esac

exit 0
